#./docker-compose.yml
version: '2'
services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
    depends_on: 
      - db
  db:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "4408:3306"